version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mentorhub-node
    working_dir: /app
    stdin_open: true
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - mentorhub-net

  frontend-nginx:
    image: nginx:alpine
    container_name: mentorhub-node-nginx
    ports:
      - "3000:80"
    working_dir: /app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - node
    networks:
      - mentorhub-net

networks:
  mentorhub-net:
    external: true
    name: mentorhub-net