services:
  nginx:
    image: nginx:alpine
    container_name: mentorhub-nginx
    ports:
      - "8001:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mentorhub-net

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mentorhub-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=mentorhub
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_pass
    depends_on:
      - postgres
    networks:
      - mentorhub-net

  postgres:
    image: postgres:16
    container_name: mentorhub-postgres
    environment:
      POSTGRES_DB: mentorhub
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mentorhub-net

networks:
  mentorhub-net:
    driver: bridge
    name: mentorhub-net

volumes:
  postgres_data: